from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
PREPARE = ROOT / "scripts" / "prepare_humanize_task.py"
CONTRACT = ROOT / "examples" / "task_contracts" / "training-rollout-mismatch-debug.yaml"


def no_codex_env() -> dict[str, str]:
    env = dict(os.environ)
    env["PATH"] = ""
    env.pop("HUMANIZE_ROOT", None)
    return env


def run_prepare(args: list[str], *, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(PREPARE), *args],
        cwd=ROOT,
        text=True,
        capture_output=True,
        env=env,
    )


def load_bridge_module():
    spec = importlib.util.spec_from_file_location("prepare_humanize_task", PREPARE)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_prepare_humanize_task_creates_humanize_ready_workspace_with_warnings(tmp_path):
    workspace = tmp_path / "workspace"
    target_repo = tmp_path / "target-repo"
    target_repo.mkdir()

    result = run_prepare(
        [
            "--contract",
            str(CONTRACT),
            "--workspace",
            str(workspace),
            "--target-repo",
            str(target_repo),
            "--diff-base",
            "main",
            "--force",
            "--overwrite-human-docs",
        ],
        env=no_codex_env(),
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "WARN: codex CLI not found" in result.stdout

    start = workspace / "humanize_start.md"
    metadata_path = workspace / ".humanize" / "rlinfra_bridge.json"
    plan_lock = workspace / ".humanize" / "plan.lock.md"
    assert start.exists()
    assert metadata_path.exists()
    assert plan_lock.exists()

    start_text = start.read_text(encoding="utf-8")
    assert f"Workspace path: `{workspace.resolve()}`" in start_text
    assert f"Contract path: `{CONTRACT.resolve()}`" in start_text
    assert f"Target repo: `{target_repo.resolve()}`" in start_text
    assert "Diff base: `main`" in start_text
    assert "Do **not** launch Claude Code" in start_text
    assert "launch_humanize.sh" in start_text
    assert "git add -f .humanize" in start_text
    assert "generated by scripts/prepare_humanize_task.py" in start_text
    assert "Main repo commit:" in start_text
    assert "Pinned RLInfraWiki commit:" in start_text
    assert "Preserve RLInfraWiki page IDs and source IDs" in start_text
    assert "source-reported" in start_text
    assert "docs/validation_matrix.md" in start_text
    assert "docs/risk_register.md" in start_text

    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    assert metadata["schema_version"] == 2
    assert metadata["execution_mode"] == "target_repo"
    assert metadata["repo_commit"] is None
    assert metadata["rlinfrawiki_commit"] is None
    assert metadata["contract"] == str(CONTRACT.resolve())
    assert metadata["workspace"] == str(workspace.resolve())
    assert metadata["target_repo"] == str(target_repo.resolve())
    assert metadata["target_repo_status"]["path"] == str(target_repo.resolve())
    assert metadata["diff_base"] == "main"
    assert metadata["plan_lock"] == str(plan_lock.resolve())
    assert metadata["humanize_start"] == str(start.resolve())
    assert metadata["next_command"] is None
    assert set(metadata["context_paths"]) == {"markdown", "json", "sources"}
    assert "humanize_instruction_files" in metadata["prerequisites"]
    assert "repository_instruction_files" in metadata["prerequisites"]
    assert any("codex CLI not found" in warning for warning in metadata["prereq_warnings"])
    assert any("git CLI not found" in warning for warning in metadata["prereq_warnings"])
    assert [row["name"] for row in metadata["commands_run"]] == [
        "render_task_bundle",
        "validate_context_bundle",
        "lock_plan",
        "validate_review_gate",
    ]
    for row in metadata["commands_run"]:
        assert "timeout_seconds" in row
        assert "stdout_truncated" in row
        assert "stderr_truncated" in row

    for rel_path in [
        "context/context_bundle.md",
        "context/context_bundle.json",
        "context/context_sources.yaml",
    ]:
        assert (workspace / rel_path).exists(), rel_path


def test_prepare_humanize_task_missing_contract_fails(tmp_path):
    result = run_prepare(
        [
            "--contract",
            str(tmp_path / "missing.yaml"),
            "--workspace",
            str(tmp_path / "workspace"),
        ]
    )

    assert result.returncode != 0
    assert "missing contract" in result.stderr


def test_prepare_humanize_task_strict_prereqs_fails_on_missing_codex(tmp_path):
    workspace = tmp_path / "strict-workspace"
    result = run_prepare(
        [
            "--contract",
            str(CONTRACT),
            "--workspace",
            str(workspace),
            "--force",
            "--overwrite-human-docs",
            "--strict-prereqs",
        ],
        env=no_codex_env(),
    )

    assert result.returncode == 2
    assert "--strict-prereqs requested" in result.stderr
    metadata = json.loads((workspace / ".humanize" / "rlinfra_bridge.json").read_text(encoding="utf-8"))
    assert any("codex CLI not found" in warning for warning in metadata["prereq_warnings"])
    assert any("git CLI not found" in warning for warning in metadata["prereq_warnings"])


def test_prerequisite_detection_reports_missing_humanize_side_docs_even_when_repo_docs_exist(tmp_path):
    bridge = load_bridge_module()
    isolated_repo = tmp_path / "isolated" / "rl-infra-design-agents"
    (isolated_repo / "integrations" / "humanize").mkdir(parents=True)
    (isolated_repo / "docs").mkdir()
    (isolated_repo / "integrations" / "humanize" / "README.md").write_text("repo humanize docs\n", encoding="utf-8")
    (isolated_repo / "docs" / "humanize-compatible-rlcr.md").write_text("repo rlcr docs\n", encoding="utf-8")
    (isolated_repo / "CLAUDE.md").write_text("repo claude docs\n", encoding="utf-8")

    prereqs = bridge.detect_prerequisites(isolated_repo, env={}, path="")

    assert prereqs["humanize_roots"] == []
    assert prereqs["humanize_instruction_files"] == []
    assert len(prereqs["repository_instruction_files"]) == 3
    assert prereqs["codex_cli"] is None
    assert any("Humanize root not found" in warning for warning in prereqs["warnings"])
    assert any("codex CLI not found" in warning for warning in prereqs["warnings"])
    assert any("Humanize-side Claude Code/Humanize instruction files" in warning for warning in prereqs["warnings"])


def test_truncate_stream_marks_long_output():
    bridge = load_bridge_module()
    short_text, short_truncated = bridge.truncate_stream("short output")
    assert short_text == "short output"
    assert short_truncated is False

    long_text, long_truncated = bridge.truncate_stream("x" * (bridge.MAX_COMMAND_OUTPUT_CHARS + 10))
    assert long_truncated is True
    assert long_text.startswith("x" * bridge.MAX_COMMAND_OUTPUT_CHARS)
    assert f"truncated to {bridge.MAX_COMMAND_OUTPUT_CHARS} characters" in long_text


def test_target_repo_status_warns_for_non_git_and_bad_diff_base(tmp_path):
    bridge = load_bridge_module()
    non_git = tmp_path / "non-git"
    non_git.mkdir()

    status, warnings = bridge.target_repo_status(non_git, "main")
    assert status["provided"] is True
    assert status["is_git_repo"] is False
    assert any("not a git repository" in warning or "git is unavailable" in warning for warning in warnings)

    git_repo = tmp_path / "git-repo"
    git_repo.mkdir()
    init = subprocess.run(["git", "init"], cwd=git_repo, text=True, capture_output=True)
    if init.returncode != 0:
        pytest.skip("git init unavailable in this test environment")

    status, warnings = bridge.target_repo_status(git_repo, "no-such-branch")
    assert status["is_git_repo"] is True
    assert status["diff_base_resolves"] is False
    assert any("diff base does not resolve" in warning for warning in warnings)
